import { useRef, useState } from "react";
import { applyAutoArtistPrefix, prefixConfirmedArtistsInText, previewAutoArtistPrefix, reapplyQuickArtistPrefixChanges, revertQuickArtistPrefixChanges, type ArtistTextPrefixResult, type AutoArtistPrefixPreview } from "../../../lib/api";
import { notifyMainStateChanged } from "../../../lib/windows/library-events";
import { openRowInMainWindow } from "../../../lib/windows/toolbox";
import { errorText, formatCount } from "../../../lib/utils/format";
import { recordHistory, useHistory } from "../../state/history";
import { runTask, useTasks } from "../../state/tasks";
import { notify } from "../../state/notices";
import { Button, Checkbox, Input, Textarea } from "../../ui/controls";
import { ToolCard, ToolError, ToolMetrics, ToolPage } from "./shared";

export default function ArtistPrefixTool() {
  const [preview, setPreview] = useState<AutoArtistPrefixPreview | null>(null), [selected, setSelected] = useState<string[]>([]), [search, setSearch] = useState(""), [text, setText] = useState(""), [result, setResult] = useState<ArtistTextPrefixResult | null>(null), [error, setError] = useState<string | null>(null), [operation, setOperation] = useState<string | null>(null), [opening, setOpening] = useState<number | null>(null);
  const running = useRef(false), taskBusy = useTasks(state => state.busy), historyBusy = useHistory(state => state.busy), busy = taskBusy || historyBusy || !!operation;
  const candidates = (preview?.candidates ?? []).filter(candidate => candidate.matchName.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
  async function perform(label: string, action: () => Promise<void>) { if (running.current || busy) return; running.current = true; setOperation(label); setError(null); try { await runTask(label, action); } catch (cause) { setError(errorText(cause)); } finally { setOperation(null); running.current = false; } }
  async function scan() { const value = await previewAutoArtistPrefix(); setPreview(value); setSelected(value.candidates.map(item => item.matchName)); }
  async function apply() {
    if (!selected.length) return;
    await perform("正在应用…", async () => {
      const value = await applyAutoArtistPrefix(selected);
      if (value.changes.length) { const changes = value.changes.map(change => ({ ...change })); const invalidate = async () => { setPreview(null); setSelected([]); await notifyMainStateChanged("libraryEdited"); }; recordHistory({ label: `自动补全画师前缀（${formatCount(value.changedRows)} 张）`, undo: async () => { await revertQuickArtistPrefixChanges(changes); await invalidate(); }, redo: async () => { await reapplyQuickArtistPrefixChanges(changes); await invalidate(); } }); }
      await notifyMainStateChanged("libraryEdited"); notify(value.changedRows ? `自动修正完成：${formatCount(value.changedRows)} 张图片的 ${formatCount(value.promptFieldsChanged)} 个提示词字段已更新。` : "所选候选没有产生修改。");
      try { await scan(); } catch { setPreview(null); setSelected([]); }
    });
  }
  return <ToolPage><ToolCard><small>LIBRARY ARTIST EVIDENCE</small><h3>补全库内裸画师 Tag</h3><p>如果资料库中某处已有 artist:xy，就把其它提示词中的裸 xy 视为同一画师并补上前缀。没有库内明确证据的名称不会进入候选。</p></ToolCard><ToolCard><div className="rt-row"><div><h3>处理纯文本</h3><p>粘贴提示词后，只为资料库中已有明确标注的同名裸画师 Tag 补上前缀，不会修改资料库。</p></div><Button variant="primary" disabled={busy || !text.trim()} onClick={() => void perform("处理文本…", async () => setResult(await prefixConfirmedArtistsInText(text)))}>{operation === "处理文本…" ? "处理中…" : "添加 artist: 前缀"}</Button></div><div className={`rt-columns ${result ? "" : "rt-single"}`}><label className="rt-field">原始文本<Textarea rows={8} disabled={busy} value={text} onChange={event => { setText(event.target.value); setResult(null); }} placeholder="在这里粘贴 NovelAI 提示词…" /></label>{result && <label className="rt-field">处理结果<Textarea rows={8} value={result.text} readOnly /></label>}</div>{result && <div className="rt-row"><p>{result.matchedArtists.length ? `已识别 ${formatCount(result.matchedArtists.length)} 个库内画师，并保留原始格式。` : "没有发现需要补前缀的库内画师，原文保持不变。"}</p><Button onClick={() => void navigator.clipboard.writeText(result.text).then(() => notify("处理后的纯文本已复制到剪贴板。")).catch(cause => notify(`复制失败：${errorText(cause)}`, "error"))}>复制结果</Button></div>}</ToolCard>
    <ToolCard className="rt-row"><div><h3>扫描资料库</h3><p>只处理已经入库的提示词，不联网，也不重新读取或改写原始图片文件。</p></div><Button variant="primary" disabled={busy} onClick={() => void perform("扫描中…", scan)}>扫描裸画师 Tag</Button></ToolCard><ToolError error={error} />
    {preview && <ToolCard><ToolMetrics items={[[preview.scannedRows, "扫描图片"], [preview.matchedRows, "命中图片"], [preview.candidates.length, "确认画师"], [preview.promptFieldsNeedingChanges, "提示词字段"]]} />{preview.candidates.length ? <><div className="rt-row"><Input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="搜索画师名称" /><Button variant="ghost" disabled={busy} onClick={() => setSelected(preview.candidates.map(item => item.matchName))}>全选</Button><Button variant="ghost" disabled={busy} onClick={() => setSelected([])}>清空</Button></div><div className="rt-candidates">{candidates.map(candidate => <div className="rt-candidate" key={candidate.matchName}><Checkbox aria-label={`选择 ${candidate.displayName}`} disabled={busy} checked={selected.includes(candidate.matchName)} onCheckedChange={checked => setSelected(values => checked ? [...values, candidate.matchName] : values.filter(value => value !== candidate.matchName))} /><div><strong>{candidate.displayName}</strong><small>库内已有明确 artist: 标注</small></div><div><strong>{formatCount(candidate.matchedRows)} 张</strong><small>{formatCount(candidate.matchedFields)} 个字段</small></div><Button variant="ghost" disabled={!candidate.sampleRowIds.length || opening !== null} onClick={() => { const id = candidate.sampleRowIds[0]; setOpening(id); void openRowInMainWindow(id).catch(cause => notify(errorText(cause), "error")).finally(() => setOpening(null)); }}>查看示例</Button></div>)}</div><div className="rt-row"><p>已选择 {formatCount(selected.length)} 个画师</p><Button variant="primary" disabled={busy || !selected.length} onClick={() => void apply()}>{operation === "正在应用…" ? operation : "为所选画师补全前缀"}</Button></div></> : <div className="rt-empty"><strong>没有发现能够由库内证据确认的裸画师 Tag</strong><p>只有同时存在明确 artist: 标注的同名 Tag 才会被识别。</p></div>}</ToolCard>}</ToolPage>;
}
