import { ArrowDown, ArrowUp, CheckCircle2, ClipboardCopy, ClipboardPaste, FlaskConical, Import, Plus, Save, Trash2, Zap } from "lucide-react";
import { formatCount } from "../../../lib/utils/format";
import { useAutomationRules } from "../../state/tools/automation-rules";
import { useTasks } from "../../state/tasks";
import { Button, Checkbox, Input, Menu, Modal, Textarea, type MenuItem } from "../../ui/controls";
import { Thumbnail } from "../../ui/Thumbnail";
import { RuleActionEditor, RuleCheck, RuleConditionEditor, RuleSelect } from "./automation-editors";
import "./automation-rules.css";

export default function AutomationRulesTool() {
  const c = useAutomationRules();
  const taskBusy = useTasks(state => state.busy);
  const busy = c.saving || c.testing || c.running || c.deleting || c.transferring || c.reordering || taskBusy;
  const change = (action: () => void) => { action(); c.resetResult(); };
  const exportItems: MenuItem[] = [
    ...(c.selectedRule ? [{ label: "导出当前规则", hint: "导出已保存版本", action: () => void c.chooseRuleExport([c.selectedRule!.id], c.selectedRule!.name) }] : []),
    { label: "导出全部规则", hint: `${c.rules.length} 条已保存规则`, action: () => void c.chooseRuleExport(c.rules.map(rule => rule.id), "自动规则") },
  ];
  if (c.loading) return <div className="center-state empty-state"><span className="spinner" aria-hidden="true" />正在读取规则…</div>;
  return <div className="automation-rules">
    <div className="rules-layout"><aside className="rules-sidebar"><div className="sidebar-head"><div><strong>规则列表</strong><span>{c.rules.length} 条</span></div><Button variant="primary" size="sm" disabled={busy} onClick={() => c.startNew()}><Plus size={15} />新建</Button></div>
      <div className="sidebar-transfer"><Button size="sm" disabled={busy} onClick={() => void c.chooseRuleImport()}><Import size={14} />导入 JSON</Button><Menu variant="default" label="导出 JSON" items={exportItems} disabled={busy || !c.rules.length} /><Button size="sm" className="wide-transfer" disabled={busy} onClick={() => c.openRuleTextImport()}><ClipboardPaste size={14} />粘贴 JSON 文本</Button><Button size="sm" className="wide-transfer" disabled={busy || c.copyingPrompt} onClick={() => void c.copyAiRulePrompt()}><ClipboardCopy size={14} />{c.copyingPrompt ? "正在准备…" : "复制 AI 编写提示词"}</Button></div>
      {c.rules.length === 0 ? <div className="empty-rules empty-state"><Zap size={24} /><strong>还没有规则</strong><p>新建一条规则后，导入图片时就能自动整理。</p></div> : <div className="rule-list">{c.rules.map((rule, index) => <article key={rule.id} className={`${c.selectedId === rule.id ? "is-selected" : ""} ${!rule.enabled ? "is-disabled" : ""}`}><button type="button" className="rule-main" disabled={busy} onClick={() => c.loadRule(rule, true)}><span className="rule-order tabular">{index + 1}</span><span className="rule-copy"><strong title={rule.name}>{rule.name || "未命名规则"}</strong><span className="rule-sub">{c.ruleSubtitle(rule)}</span></span></button><div className="rule-side"><div className="rule-move"><Button size="icon" variant="ghost" aria-label={`上移规则「${rule.name}」`} disabled={busy || index === 0} onClick={() => void c.moveRule(index, -1)}><ArrowUp size={13} /></Button><Button size="icon" variant="ghost" aria-label={`下移规则「${rule.name}」`} disabled={busy || index === c.rules.length - 1} onClick={() => void c.moveRule(index, 1)}><ArrowDown size={13} /></Button></div><Checkbox aria-label={`${rule.enabled ? "停用" : "启用"}规则「${rule.name}」`} checked={rule.enabled} disabled={busy} onCheckedChange={value => void c.toggleRule(rule, value === true)} /></div></article>)}</div>}
    </aside><main className="rule-editor"><header className="editor-head"><div><span className="eyebrow">{c.selectedId === null ? "新规则" : `规则 #${c.selectedId}`}</span><h2 title={c.draft.name}>{c.draft.name.trim() || "未命名规则"}</h2></div><div className="editor-actions">{c.selectedRule && <Button variant="danger" disabled={busy} onClick={() => void c.removeSelectedRule()}><Trash2 size={15} />删除</Button>}<Button variant="primary" disabled={busy || !c.dirty} onClick={() => void c.saveRule()}><Save size={15} />{c.saving ? "保存中…" : "保存规则"}</Button></div></header>
      {c.error && <div className="error-banner" role="alert">{c.error}</div>}
      <fieldset className="editor-body" disabled={busy} aria-busy={busy}>
        <section className="editor-section tool-card"><SectionTitle step={1} title="名称与触发时机" description="说明这条规则何时参与自动处理。" /><div className="field-grid"><label className="automation-field"><span>规则名称</span><Input value={c.draft.name} placeholder="例如：识别某个角色" onChange={event => change(() => { c.draft.name = event.target.value; })} /></label><label className="automation-field"><span>说明（可选）</span><Input value={c.draft.description} placeholder="记录这条规则的用途" onChange={event => change(() => { c.draft.description = event.target.value; })} /></label></div><div className="trigger-row"><RuleCheck value={c.draft.enabled} onChange={value => change(() => { c.draft.enabled = value; })}>启用规则</RuleCheck><RuleCheck value={c.draft.runOnImport} onChange={value => change(() => { c.draft.runOnImport = value; })}>新图片导入后自动执行</RuleCheck><RuleCheck value={c.draft.runOnUpdate} onChange={value => change(() => { c.draft.runOnUpdate = value; })}>更新现有图片后自动执行</RuleCheck></div></section>
        <section className="editor-section tool-card"><SectionTitle step={2} title="条件检查" description="每张图片单独判断；条件组可以表达 AND 与 OR。" /><div className="logic-toolbar"><RuleSelect label="条件组之间" value={c.draft.conditions.mode} options={[["any", "满足任意一组（OR）"], ["all", "必须满足全部组（AND）"]]} onChange={value => change(() => { c.draft.conditions.mode = value as "all" | "any"; })} /><RuleSelect label="执行时机" value={c.draft.conditions.negate ? "notMatched" : "matched"} options={[["matched", "条件成立时执行"], ["notMatched", "条件不成立时执行"]]} onChange={value => change(() => { c.draft.conditions.negate = value === "notMatched"; })} /><span className="logic-summary">共 {c.draft.conditions.groups.length} 组、{c.conditionCount} 个条件</span></div>
          <div className="condition-groups">{c.draft.conditions.groups.map((group, groupIndex) => <article className="condition-group" key={groupIndex}><header><div><strong>条件组 {groupIndex + 1}</strong><RuleSelect label={`条件组 ${groupIndex + 1} 的逻辑`} value={group.mode} options={[["all", "组内条件全部成立（AND）"], ["any", "组内任意条件成立（OR）"]]} onChange={value => change(() => { group.mode = value as "all" | "any"; })} /></div><Button size="sm" variant="danger" disabled={c.draft.conditions.groups.length === 1} onClick={() => c.removeGroup(groupIndex)}>删除组</Button></header><div className="condition-list">{group.conditions.map((condition, conditionIndex) => <RuleConditionEditor key={`${conditionIndex}-${condition.type}`} condition={condition} groups={c.groups} onReplace={value => c.replaceCondition(groupIndex, conditionIndex, value)} onRemove={() => c.removeCondition(groupIndex, conditionIndex)} />)}</div><Button variant="ghost" size="sm" className="add-inline" onClick={() => c.addCondition(groupIndex)}><Plus size={14} />添加条件</Button></article>)}</div><Button onClick={() => c.addGroup()}><Plus size={15} />添加条件组</Button></section>
        <section className="editor-section tool-card"><SectionTitle step={3} title="执行任务" description="任务按从上到下的顺序执行；后续规则能看到这些修改。" /><div className="action-list">{c.draft.actions.map((action, index) => <RuleActionEditor key={`${index}-${action.type}`} action={action} groups={c.groups} tags={c.tags} tagsLoading={c.tagsLoading} onRefreshTags={c.refreshTags} onReplace={value => c.replaceAction(index, value)} onRemove={() => c.removeAction(index)} onMove={offset => c.moveAction(index, offset)} canMoveUp={index > 0} canMoveDown={index < c.draft.actions.length - 1} />)}</div><div className="add-action"><Button onClick={() => c.addAction()}><Plus size={15} />添加任务</Button></div></section>
        <section className="editor-section tool-card"><SectionTitle step={4} title="测试与应用" description="测试只读取资料库，未保存的草稿也能直接测试；应用现有图片前会再次确认。" />{(c.selectedId === null || c.dirty) && <p className="test-hint">当前是{c.selectedId === null ? "未保存的新规则" : "有未保存修改的规则"}：可以直接测试查看命中效果；“应用到现有图片”与导入时自动执行需要先保存。</p>}<div className="test-actions"><Button onClick={() => void c.testRule()}><FlaskConical size={15} />{c.testing ? "测试中…" : "测试现有资料库"}</Button><Button variant="primary" disabled={!c.preview || c.selectedId === null || c.dirty || c.preview.rowsNeedingChanges === 0} onClick={() => void c.runOnLibrary()}><Zap size={15} />{c.running ? "执行中…" : "应用到现有图片"}</Button></div>
          {c.preview && <><div className="preview-summary metric-grid tabular">{[["扫描", c.preview.scannedRows], ["命中", c.preview.matchedRows], ["需要修改", c.preview.rowsNeedingChanges], ["停止后续", c.preview.stoppedRows]].map(([label, count]) => <div key={label}><span>{label}</span><strong>{formatCount(Number(count))}</strong></div>)}</div>{c.preview.matchedRows === 0 && <div className="result-empty">没有图片命中当前规则。</div>}{c.preview.matchedRows > 0 && c.preview.rowsNeedingChanges === 0 && <div className="result-empty">当前规则不会对现有图片产生可保存的修改，无需手动应用。</div>}</>}
          {c.execution && <div className="execution-result"><CheckCircle2 size={18} /><div><strong>执行完成，修改 {formatCount(c.execution.changedRows)} 张图片</strong>{c.execution.engineError && <p className="error-line">{c.execution.engineError}</p>}{c.execution.reports.map((report, index) => <p key={`${report.ruleId}-${index}`} className={report.error ? "error-line" : ""}>{report.ruleName}：命中 {formatCount(report.matchedRows)}，修改 {formatCount(report.changedRows)}{report.error ? `；失败：${report.error}` : ""}</p>)}</div></div>}
          {c.sampleRows.length > 0 && <div className="sample-grid" aria-label="命中示例">{c.sampleRows.map(row => <button type="button" key={row.id} title="在主窗口查看" disabled={c.openingRowId === row.id} onClick={() => void c.openInMain(row.id)}><Thumbnail rowId={row.id} alt={`规则命中图片 ${row.id}`} /><span>#{row.id}</span></button>)}</div>}
        </section>
      </fieldset>
    </main></div>
    <RuleImportDialogs controller={c} />
  </div>;
}

function SectionTitle({ step, title, description }: { step: number; title: string; description: string }) {
  return <div className="section-title"><span className="step-badge">{step}</span><div><h3>{title}</h3><p>{description}</p></div></div>;
}

function RuleImportDialogs({ controller: c }: { controller: ReturnType<typeof useAutomationRules> }) {
  const bytes = new TextEncoder().encode(c.importText).length;
  const tooLarge = bytes > 2 * 1024 * 1024;
  const inspection = c.importInspection;
  const pending = c.pendingImport;
  const sourceName = pending?.kind === "file" ? pending.path.split(/[\\/]/).pop() ?? pending.path : "粘贴的 JSON 文本";
  return <><Modal open={c.textImportOpen} title="粘贴 JSON 文本" description="可粘贴纯 JSON，或 AI 回复中的一个 json 代码块。" width={680} busy={c.transferring} onClose={c.closeRuleTextImport} footer={<><Button disabled={c.transferring} onClick={c.closeRuleTextImport}>取消</Button><Button variant="primary" disabled={c.transferring || tooLarge || !c.importText.trim()} onClick={() => void c.inspectRuleText()}>{c.transferring ? "检查中…" : "检查并预览"}</Button></>}><div className="automation-dialog"><label className="automation-field"><span>规则 JSON</span><Textarea className="automation-json" rows={14} value={c.importText} disabled={c.transferring} spellCheck={false} placeholder={'粘贴 { "format": "smart-spreadsheet-automation-rules", ... }\n\n也支持粘贴含有 ```json 代码块的 AI 回复。'} onChange={event => c.updateRuleText(event.target.value)} /></label><div className="automation-text-meta"><span>这里只检查内容，不会立即写入资料库。</span><span>{(bytes / 1024).toFixed(bytes >= 1024 ? 1 : 0)} KB / 2048 KB</span></div>{(tooLarge || c.textImportError) && <p className="automation-inline-error" role="alert">{tooLarge ? "粘贴内容超过 2 MB 上限，请减少规则数量后重试。" : c.textImportError}</p>}</div></Modal>
    <Modal open={!!inspection && !!pending} title="确认导入规则" description={sourceName} width={620} busy={c.transferring} onClose={c.closeRuleImport} footer={<>{pending?.kind === "text" && <Button className="automation-back" disabled={c.transferring} onClick={c.backToRuleText}>返回修改</Button>}<Button disabled={c.transferring} onClick={c.closeRuleImport}>取消</Button><Button variant="primary" disabled={c.transferring} onClick={() => void c.confirmRuleImport()}>{c.transferring ? "导入中…" : `导入 ${inspection?.ruleCount ?? 0} 条规则`}</Button></>}>
      {inspection && <div className="automation-dialog"><div className="automation-summary"><strong>{inspection.ruleCount} 条规则</strong><span>JSON 格式版本 {inspection.version}</span></div><div className="automation-rule-preview" aria-label="待导入规则">{inspection.rules.map((rule, index) => <article key={index}><span>{index + 1}</span><div><strong>{rule.importedName}</strong>{rule.importedName !== rule.name && <span className="automation-warning">原名“{rule.name}”，因重名自动改名</span>}<small>{[rule.runOnImport && "导入", rule.runOnUpdate && "更新"].filter(Boolean).join("＋") || "仅手动"} · {rule.conditionCount} 个条件 · {rule.actionCount} 个任务</small></div></article>)}</div>{(inspection.missingTags.length > 0 || inspection.missingGroups.length > 0) && <section className="automation-dependencies"><h3>将随规则创建的项目</h3><p>这些名称来自规则文件；确认导入后才会写入当前资料库。</p>{[["Tag", inspection.missingTags], ["分组", inspection.missingGroups]].map(([label, values]) => { const names = values as string[]; return names.length > 0 && <div key={String(label)}><strong>{String(label)}（{names.length}）</strong><div className="automation-chips">{names.slice(0, 12).map(name => <span key={name}>{name}</span>)}{names.length > 12 && <span>＋{names.length - 12}</span>}</div></div>; })}</section>}<p className="automation-warning"><strong>导入后的规则全部保持停用。</strong>请逐条检查条件和任务，确认无误后再手动启用。</p></div>}
    </Modal></>;
}
