import { useRef, useState } from "react";
import { listen } from "@tauri-apps/api/event";
import { open, save } from "@tauri-apps/plugin-dialog";
import { dedupeZhihuijiJson, inspectZhihuijiJson, type JsonDedupeInspection, type JsonDedupeProgress, type JsonDedupeSummary } from "../../../lib/api";
import { errorText, formatCount } from "../../../lib/utils/format";
import { useTasks, runTask } from "../../state/tasks";
import { Button } from "../../ui/controls";
import { ToolCard, ToolPage, ToolError, ToolMetrics, ToolProgress, fileName } from "./shared";
export default function JsonDedupeView() {
  const [path, setPath] = useState<string | null>(null), [inspection, setInspection] = useState<JsonDedupeInspection | null>(null), [summary, setSummary] = useState<JsonDedupeSummary | null>(null), [progress, setProgress] = useState<JsonDedupeProgress | null>(null), [error, setError] = useState<string | null>(null), [working, setWorking] = useState(false);
  const busy = useTasks(state => state.busy), operation = useRef(false);
  async function perform(action: () => Promise<void>) { if (operation.current || busy) return; operation.current = true; setWorking(true); setError(null); try { await action(); } catch (cause) { setError(errorText(cause)); } finally { operation.current = false; setWorking(false); } }
  async function pick() { await perform(async () => { const value = await open({ multiple: false, directory: false, title: "选择智绘姬 JSON 文件", filters: [{ name: "JSON 文件", extensions: ["json"] }] }); if (typeof value !== "string") return; setSummary(null); setInspection(null); setPath(value); await runTask("检查 JSON", async () => setInspection(await inspectZhihuijiJson(value))); }); }
  async function dedupe() { if (!path || !inspection) return; await perform(async () => { const output = await save({ title: "保存去重后的 JSON（不能与输入文件相同）", defaultPath: fileName(path).replace(/\.json$/i, "_去重.json"), filters: [{ name: "JSON 文件", extensions: ["json"] }] }); if (typeof output !== "string") return;
    await runTask("JSON 去重", async () => { let cleanup: (() => void) | undefined; setSummary(null); try { cleanup = await listen<JsonDedupeProgress>("json-dedupe://progress", event => setProgress(event.payload)); setSummary(await dedupeZhihuijiJson(path, output)); } finally { cleanup?.(); setProgress(null); } }); }); }
  return <ToolPage narrow><ToolCard><p>按 fixedPrompt 去除重复预设并重新连续编号，原文件不会被修改。</p><div className="rt-row"><Button disabled={working || busy} onClick={() => void pick()}>选择 JSON 文件</Button>{path && <code title={path}>{fileName(path)}</code>}</div><ToolError error={error} />{inspection && <><ToolMetrics items={[[inspection.originalCount, "预设总数"], [inspection.duplicateCount, "重复"], [inspection.uniqueCount, "去重后"]]} />{inspection.preview.length > 0 && <div><p>内容预览（前 {inspection.preview.length} 条）：</p>{inspection.preview.map(item => <p className="rt-preview-line" key={item.presetKey} title={item.fixedPrompt}>#{item.presetKey}　{item.fixedPrompt || "（空 fixedPrompt）"}</p>)}</div>}{progress && <ToolProgress value={progress.processed} total={progress.total} label={`正在去重，已发现重复 ${formatCount(progress.duplicateCount)} 条`} />}{summary && <p className="rt-success" role="status">完成：去除 {formatCount(summary.duplicateCount)} 条重复，保留 {formatCount(summary.uniqueCount)} 条，已保存到 {summary.outputPath}</p>}</>}<div className="rt-row rt-footer"><small>{inspection ? inspection.duplicateCount ? `可去除 ${formatCount(inspection.duplicateCount)} 条重复预设` : "没有重复预设，无需去重" : "请先选择文件"}</small><Button variant="primary" disabled={busy || working || !inspection?.duplicateCount} onClick={() => void dedupe()}>{working ? "处理中…" : "去重并另存为…"}</Button></div></ToolCard></ToolPage>;
}
